export const purchasesData = 
[
    {
        name: 'Jan',
        "Purchases": 4000,
    },
    {
        name: 'Feb',
        "Purchases": 3000,
    },
    {
        name: 'Mar',
        "Purchases": 2000,
    },
    {
        name: 'Apr',
        "Purchases": 2780,
    },
    {
        name: 'May',
        "Purchases": 1890,
    },
    {
        name: 'Jun',
        "Purchases": 2390,
    },
    {
        name: 'Jul',
        "Purchases": 4000,
    },
    {
        name: 'Aug',
        "Purchases": 3000,
    },
    {
        name: 'Sep',
        "Purchases": 2000,
    },
    {
        name: 'Oct',
        "Purchases": 2780,
    },
    {
        name: 'Nov',
        "Purchases": 1890,
    },
    {
        name: 'Dec',
        "Purchases": 2390,
    },
];

export const productRows = [
    { 
        id: 1, 
        name: 'Goat Meat', 
        quantity: 200, 
        stockDate: '02 Jan 2021', 
        category: 'Frozen Foods', 
        avatar: 'https://res.cloudinary.com/foodcrowdy/image/upload/v1622635084/products/edwzkkvy1oprf3g1rnud.jpg', 
        status: 'In Stock',
    },
    { 
        id: 2, 
        name: 'Frozen Chicken', 
        quantity: 100, 
        stockDate: '02 Jan 2021', 
        category: 'Frozen Foods', 
        avatar: 'https://res.cloudinary.com/foodcrowdy/image/upload/v1622454446/products/btkayraqyy2pels9wo4t.jpg', 
        status: 'In Stock',
    },
    { 
        id: 3, 
        name: 'Panla', 
        quantity: 0, 
        stockDate: '02 Jan 2021', 
        category: 'Frozen Foods', 
        avatar: 'https://res.cloudinary.com/foodcrowdy/image/upload/v1624291608/products/cnnlt4hr1dqrxxofiatp.png', 
        status: 'Out Of Stock',
    },
    { 
        id: 4, 
        name: 'White Beans', 
        quantity: 5, 
        stockDate: '02 Jan 2021', 
        category: 'Grains', 
        avatar: 'https://res.cloudinary.com/foodcrowdy/image/upload/v1622294686/products/ul8mli8fmha4lqejuxej.jpg', 
        status: 'Low Stock',
    },
    { 
        id: 5, 
        name: 'Mackerel', 
        quantity: 50, 
        stockDate: '02 Jan 2021', 
        category: 'Frozen Foods', 
        avatar: 'https://res.cloudinary.com/foodcrowdy/image/upload/v1624261563/products/trj3pxylcyu8oj6tqnml.jpg', 
        status: 'Low Stock',
    },
    { 
        id: 6, 
        name: 'Goat Meat', 
        quantity: 200, 
        stockDate: '02 Jan 2021', 
        category: 'Frozen Foods', 
        avatar: 'https://res.cloudinary.com/foodcrowdy/image/upload/v1622635084/products/edwzkkvy1oprf3g1rnud.jpg', 
        status: 'In Stock',
    },
    { 
        id: 7, 
        name: 'Frozen Chicken', 
        quantity: 100, 
        stockDate: '02 Jan 2021', 
        category: 'Frozen Foods', 
        avatar: 'https://res.cloudinary.com/foodcrowdy/image/upload/v1622454446/products/btkayraqyy2pels9wo4t.jpg', 
        status: 'In Stock',
    },
    { 
        id: 8, 
        name: 'Panla', 
        quantity: 0, 
        stockDate: '02 Jan 2021', 
        category: 'Frozen Foods', 
        avatar: 'https://res.cloudinary.com/foodcrowdy/image/upload/v1624291608/products/cnnlt4hr1dqrxxofiatp.png', 
        status: 'Out Of Stock',
    },
    { 
        id: 9, 
        name: 'White Beans', 
        quantity: 5, 
        stockDate: '02 Jan 2021', 
        category: 'Grains', 
        avatar: 'https://res.cloudinary.com/foodcrowdy/image/upload/v1622294686/products/ul8mli8fmha4lqejuxej.jpg', 
        status: 'Low Stock',
    },
    { 
        id: 10, 
        name: 'Mackerel', 
        quantity: 50, 
        stockDate: '02 Jan 2021', 
        category: 'Frozen Foods', 
        avatar: 'https://res.cloudinary.com/foodcrowdy/image/upload/v1624261563/products/trj3pxylcyu8oj6tqnml.jpg', 
        status: 'Low Stock',
    },
    { 
        id: 11, 
        name: 'Goat Meat', 
        quantity: 200, 
        stockDate: '02 Jan 2021', 
        category: 'Frozen Foods', 
        avatar: 'https://res.cloudinary.com/foodcrowdy/image/upload/v1622635084/products/edwzkkvy1oprf3g1rnud.jpg', 
        status: 'In Stock',
    },
    { 
        id: 12, 
        name: 'Frozen Chicken', 
        quantity: 100, 
        stockDate: '02 Jan 2021', 
        category: 'Frozen Foods', 
        avatar: 'https://res.cloudinary.com/foodcrowdy/image/upload/v1622454446/products/btkayraqyy2pels9wo4t.jpg', 
        status: 'In Stock',
    },
    { 
        id: 13, 
        name: 'Panla', 
        quantity: 0, 
        stockDate: '02 Jan 2021', 
        category: 'Frozen Foods', 
        avatar: 'https://res.cloudinary.com/foodcrowdy/image/upload/v1624291608/products/cnnlt4hr1dqrxxofiatp.png', 
        status: 'Out Of Stock',
    },
    { 
        id: 14, 
        name: 'White Beans', 
        quantity: 5, 
        stockDate: '02 Jan 2021', 
        category: 'Grains', 
        avatar: 'https://res.cloudinary.com/foodcrowdy/image/upload/v1622294686/products/ul8mli8fmha4lqejuxej.jpg', 
        status: 'Low Stock',
    },
    { 
        id: 15, 
        name: 'Mackerel', 
        quantity: 50, 
        stockDate: '02 Jan 2021', 
        category: 'Frozen Foods', 
        avatar: 'https://res.cloudinary.com/foodcrowdy/image/upload/v1624261563/products/trj3pxylcyu8oj6tqnml.jpg', 
        status: 'Low Stock',
    },
];